<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>OfferLens</RootNamespace>
    <OutputType>WinExe</OutputType>
    <!--If you are willing to use platform-specific APIs, use conditional compilation.
    See https://docs.avaloniaui.net/docs/guides/platforms/platform-specific-code/dotnet for more details.-->
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>OfferLens</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Sandreas.Avalonia.SimplePreferences" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OfferLens\OfferLens.csproj" />
  </ItemGroup>
</Project>
